apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - host: www.mintapp.online
      http:
        paths:
          - path: /api/v1/user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: user-srv
                port:
                  number: 8000
          - path: /api/v1/course/?(.*)
            pathType: Prefix
            backend:
              service:
                name: course-srv
                port:
                  number: 8001
          - path: /api/v1/payment/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-srv
                port:
                  number: 8002
          - path: /api/v1/valuation/?(.*)
            pathType: Prefix
            backend:
              service:
                name: valuation-srv
                port:
                  number: 8003
          - path: /api/v1/realtime/?(.*)
            pathType: Prefix
            backend:
              service:
                name: realtime-srv
                port:
                  number: 8004
          - path: /api/v1/upload/?(.*)
            pathType: Prefix
            backend:
              service:
                name: cloud-srv
                port:
                  number: 8005
