apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: blearn.dev
      http:
        paths:
          - path: /api/v1/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 8000
          - path: /admin/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 8000
          - path: /courses/?(.*)
            pathType: Prefix
            backend:
              service:
                name: courses-srv
                port:
                  number: 8001
          - path: /category/?(.*)
            pathType: Prefix
            backend:
              service:
                name: courses-srv
                port:
                  number: 8001
          