apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: s7abab/payment
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: port
                  key:  PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq
                  key: RABBIT_MQ
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: REDIS_URL
            - name: REDIS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: redis-expiration-time
                  key: REDIS_EXPIRATION_TIME
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 8002
      targetPort: 8002