apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
        - name: realtime
          image: s7abab/realtime
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: port
                  key:  PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq
                  key: RABBIT_MQ
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-srv
spec:
  selector:
    app: realtime
  ports:
    - name: realtime
      protocol: TCP
      port: 3000
      targetPort: 3000