apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: s7abab/user
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: port
                  key:  PORT
            - name: ORGIN
              valueFrom:
                secretKeyRef:
                  name: orgin
                  key: ORGIN
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: user-mongo
                  key: MONGO_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: REDIS_URL
            - name: ACTIVATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: activation-secret
                  key: ACTIVATION_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: jwt-expire
                  key: JWT_EXPIRE
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-host
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-port
                  key: SMTP_PORT
            - name: SMTP_SERVICE
              valueFrom:
                secretKeyRef:
                  name: smtp-service
                  key: SMTP_SERVICE
            - name: SMTP_MAIL
              valueFrom:
                secretKeyRef:
                  name: smtp-mail
                  key: SMTP_MAIL
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-password
                  key: SMTP_PASSWORD
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq
                  key: RABBIT_MQ
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 8000
      targetPort: 8000