apiVersion: apps/v1
kind: Deployment
metadata:
  name: valuation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valuation
  template:
    metadata:
      labels:
        app: valuation
    spec:
      containers:
        - name: valuation
          image: s7abab/valuation
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: port
                  key:  PORT
            - name: ORGIN
              valueFrom:
                secretKeyRef:
                  name: orgin
                  key: ORGIN
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: valuation-mongo
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq
                  key: RABBIT_MQ
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: valuation-srv
spec:
  selector:
    app: valuation
  ports:
    - name: valuation
      protocol: TCP
      port: 8003
      targetPort: 8003