name: deploy-payment

on: 
 push:
   branches:
     - main
   paths:
     - 'payment/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Build Docker Image
       run: |
         cd payment
         docker build -t s7abab/payment .
     - name: Login to Docker Hub
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push Docker Image
       run: docker push s7abab/payment
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save blea
     - run: kubectl rollout restart deployment payment-depl
   
   
